group:
  repos: |
    mlcommons/inference
  files:
    - source: compliance/check.py
      dest: tools/submission/power/power_checker.py
    - source: compliance/sources_checksums.json
      dest: tools/submission/power/sources_checksums.json
