name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'mlcommons/power-dev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.INFERENCE_ACCESS_TOKEN }}
          TEAM_REVIEWERS: wg-inference
          SKIP_PR: false
